services:
  solr:
    ports:
      - "8983:8983"
  app:
    volumes:
      - type: bind
        source: ./static
        target: /app/static
      - type: bind
        source: ./templates
        target: /app/templates
      - type: bind
        source: ./dockerdevconfig
        target: /app/config
