version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout

      - run:
          name: Test
          command: |
            cd kawa-web-collection
            git submodule update --init
            mvn install -DskipTests=true
            cd ..
            mvn test

  build:
    machine: true
    steps:
      - checkout

      - run: |
          cd kawa-web-collection
          git submodule update --init
          cd ..
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker build -t arvyy/r7rs-index:$CIRCLE_BRANCH -f docker/Dockerfile .

      - run: docker push arvyy/r7rs-index:$CIRCLE_BRANCH

  deploy:
    machine: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "bash ~/update.sh arvyy/r7rs-index:$CIRCLE_BRANCH"

workflows:
  sample:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
