services:
  app:
    image: "r7rs-index:latest"
    volumes:
      - "statics:/app/static"

  nginx:
    image: "nginx:1.21"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "statics:/www/data:ro"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
    ports:
      - "80:80"
      - "443:443"
volumes:
  statics:
