services:
  app:
    image: "arvyy/scheme-index:master"
    volumes:
      - "statics:/app/static"
      - type: bind
        source: ./logs
        target: /app/logs

  nginx:
    image: "nginx:1.21"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "statics:/www/data:ro"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
    ports:
      - "80:80"
      - "443:443"

volumes:
  statics:
